### ISSUE TITLE
Broken version deployed

### ISSUE THREAD

**Issue by dokempf** [ssciwr/iwr-interactive-visualization#209]
I just had a look at the project and realized that the currently deployed version (to Github Pages) is broken with the following error:

![Screenshot from 2024-07-15 15-19-23](https://github.com/user-attachments/assets/92e46489-d1e8-47c0-8730-a03636932724)

**Comment by lkeegan** [comment]
Thanks - looks like this was caused by the latest dependabot update #208, have reverted this commit for now, should be working again.

**Comment by lkeegan** [comment]
Can reproduce locally by upgrading `@svgdotjs/svg.js` 3.2.0 -> 3.2.1

**Comment by lkeegan** [comment]
"fixed" by #210
