### ISSUE TITLE
todo: check on macOS

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/iwr-interactive-visualization#55]

**Comment by fsadlo** [comment]
Safari
![image](https://user-images.githubusercontent.com/43894770/161791977-c41a56eb-0844-4d0c-89da-f59dd3ef8a7a.png)

Firefox:
![image](https://user-images.githubusercontent.com/43894770/161792090-91cc9af8-6127-47f7-9979-b7fc8acdcaed.png)

**Comment by lkeegan** [comment]
Single-line svg text on safari looks ok:
![2](https://user-images.githubusercontent.com/12845624/161964088-fa5bb533-5dd4-439b-b02f-29ddfe86fae4.png)

Multi-line svg text has issues on safari:
![1](https://user-images.githubusercontent.com/12845624/161964126-a5e5ef27-3e53-4336-a933-620b45d43438.png)
![3](https://user-images.githubusercontent.com/12845624/161964226-e3b4b23e-657c-466d-b6f1-89f3f2ab7129.png)

Probably the solution would be to have a svg text element for each line with a manual `dy` vertical offset

**Comment by lkeegan** [comment]
After #87 and #88 this looks better on safari, just drop-shadows still missing (see #85):
![1](https://user-images.githubusercontent.com/12845624/161989909-88ef0d4a-7125-4502-975c-73bf732d92d0.png)
![2](https://user-images.githubusercontent.com/12845624/161989925-f7e8843a-ede0-449e-9b7c-3cb6517b316a.png)
