### ISSUE TITLE
enable selection of group boxes

### ISSUE THREAD

**Issue by fsadlo** [ssciwr/iwr-interactive-visualization#83]
On (mobile) devices, where hovering is not available, the user still needs to be able to explore the groups with respect to the weights, i.e., what would be done by hovering over the group boxes.

Could we determine that we are on mobile device, and in that case, one tap would select the box (make it gray and show its weights) and only an additional tap would open the file card? Or are there better approaches?

**Comment by lkeegan** [comment]
> On (mobile) devices, where hovering is not available, the user still needs to be able to explore the groups with respect to the weights, i.e., what would be done by hovering over the group boxes.
> 
- clicking on a group on mobile highlights the segments with the weights the same as hovering does on desktop
- the difference is that clicking also displays the group card
> Could we determine that we are on mobile device, and in that case, one tap would select the box (make it gray and show its weights) and only an additional tap would open the file card? Or are there better approaches?
- I think requiring a double click on mobile to display the group card will be a confusing UI and might result in people never finding the group cards
- From some quick googling it seems that the recommended solution for implementing hover behaviour llike this on mobile is to not do it
